# MetalLB - LoadBalancer bare-metal clusterhez
# Ez adja a külső IP-t a Gateway Service-nek
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"  # Legelőször települjön
spec:
  project: default
  
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.14.9
    
    helm:
      releaseName: metallb
  
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

