# Gateway API Experimental CRDs (TLSRoute, stb.)
# A TLSRoute az experimental channel-ben van
# Kustomize mód - mert a könyvtárban van kustomization.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api-experimental-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://github.com/nginx/nginx-gateway-fabric.git
    targetRevision: v2.3.0
    path: config/crd/gateway-api/experimental
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
