apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-app-only-webui
  labels:
    app: poc-app-only-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-app-only-webui
  template:
    metadata:
      labels:
        app: poc-app-only-webui
    spec:
      containers:
      - name: web
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: poc-app-only-webui
  labels:
    app: poc-app-only-webui
spec:
  type: ClusterIP
  selector:
    app: poc-app-only-webui
  ports:
  - name: http
    port: 80
    targetPort: http
